version: '3.1'

services:
    mongo:
        
        image: mongo:4.2.6
        env_file: .env
        ports:
        - '27017:27017'
        volumes:
        - ./mongo-volume:/data/

    api:
        container_name: main
        build:
            context: .
            dockerfile: './apps/api/Dockerfile'
        ports:
            - 3333:3333